version: 2
updates:
  - package-ecosystem: github-actions
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: weekly
      time: "03:00"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - shuritch
